# docker/local/docker-compose.yml

version: "3.8"

services:
  # ---------------------------------
  # user_front
  # ---------------------------------
  user_front:
    restart: "no"
    tty: true
    build:
      context: ../../
      dockerfile: ./docker/local/user_front/nodejs/Dockerfile
    ports:
      - "3001:3000"

    volumes:
      - ../../apps/user_front:/project
    working_dir: /project
    networks:
      - shared-network

volumes:
  db-data80:

networks:
  shared-network:
    name: ${PROJECT_NAME}-network
